export const detailFieldLabels = {
  type: "Type",
  accession: "Accession",
  status: "Status",
  accessibility: "Accessibility",
  dateCreated: "Date Submitted",
  datePublished: "Date First Published",
  dateModified: "Date Last Updated",
  title: "Title",
  name: "Name",
  description: "Description",
  organism: "Organism",
  publications: "Publications",
  grants: "Grants",
  organizations: "Organizations",
  externalLinks: "External Links",
  sameAs: "Other Identifiers",
  projectType: "Project Type",
  relevance: "Relevance",
  model: "Model",
  package: "Package",
  collectionDate: "Collection Date",
  geoLocName: "Geographic Location",
  strain: "Strain",
  host: "Host",
  isolate: "Isolate",
  derivedFrom: "Derived From",
  studyType: "Study Type",
  experimentType: "Experiment Type",
  submissionType: "Submission Type",
  instrumentModel: "Instrument Model",
  platform: "Platform",
  libraryLayout: "Library Layout",
  librarySelection: "Library Selection",
  librarySource: "Library Source",
  libraryStrategy: "Library Strategy",
  libraryName: "Library Name",
  libraryConstructionProtocol: "Library Construction Protocol",
  analysisType: "Analysis Type",
  datasetType: "Dataset Type",
  vendor: "Vendor",
} as const;

export const relatedLinkLabels = {
  panelTitle: "Related Links",
  resultCount: "Related Links",
  truncatedListName: "related links",
} as const;

export const searchResultDateLabels = {
  dateCreated: "Date Submitted",
  datePublished: "Date First Published",
  dateModified: "Date Last Updated",
  datePublishedFilter: "Date First Published",
  dateModifiedFilter: "Date Last Updated",
  datePublishedTip: "Date First Published",
  dateModifiedTip: "Date Last Updated",
  datePublishedSort: "Date First Published",
  dateModifiedSort: "Date Last Updated",
} as const;
