name: release

on:
  push:
    tags:
      - "20*" # yyyymmdd

jobs:
  create_gh_release:
    if: github.repository == 'ddbj/ddbj-search-front'
    runs-on: ubuntu-22.04
    steps:
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          gh release \
            --repo "$GITHUB_REPOSITORY" \
            create "$TAG_NAME" \
            --title "$TAG_NAME" \
            --generate-notes

  deploy_gh_pages:
    if: github.repository == 'ddbj/ddbj-search-front'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.21.1"
      - run: corepack enable
      - run: corepack prepare pnpm@10.33.1 --activate
      - run: pnpm install --frozen-lockfile
      - run: BASE_PATH=/ddbj-search-front pnpm run build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
